#!/bin/bash
# @Function
# echo each arguments on one line colorfully.
#
# @Usage
#   $ ./a2l arg1 arg2
#   $ ./a2l *.txt
#
# @author Jerry Lee


# NOTE: $'foo' is the escape sequence syntax of bash
readonly ec=$'\033' # escape char
readonly eend=$'\033[0m' # escape end

colorEcho() {
    local color="$1"
    shift
    if [ -c /dev/stdout ] ; then
        # if stdout is console, turn on color output.
        echo "$ec[1;${color}m$@$eend"
    else
        echo "$@"
    fi
}

readonly ECHO_COLORS=(37 31 32 34 33 35 56)
COUNT=0

for a in "$@"; do
    colorEcho "${ECHO_COLORS[$((COUNT++ % ${#ECHO_COLORS[@]}))]}" "$a"
done
