#!/bin/bash
# @Function
# convert to absolute path.
#
# @Usage
#   $ ./ap
#   $ ./ap a.txt ../dir1/b.txt
#
# @author Jerry Lee

[ $# -eq 0 ] && files=(.) || files=("$@")

for f in "${files[@]}" ; do
    ! [ -e $f ] && {
        echo "$f does not exists!"
        continue
    }
    readlink -f "$f"
done
