#!/bin/bash
# @Function
# cat lines colorfully. colines means COLorful LINES.
#
# @Usage
#   $ echo -n 'Hello\nWorld' | colines
#   $ colines /path/to/file1
#   $ colines /path/to/file1 /path/to/file2
#
# @online-doc https://github.com/oldratlee/useful-scripts/blob/master/docs/shell.md#beer-colines
# @author Jerry Lee (oldratlee at gmail dot com)

# NOTE: $'foo' is the escape sequence syntax of bash
readonly ec=$'\033' # escape char
readonly eend=$'\033[0m' # escape end

readonly -a ECHO_COLORS=(37 31 32 34 33 35 56)
COUNT=0
colorEcho() {
    local color="${ECHO_COLORS[$((COUNT++ % ${#ECHO_COLORS[@]} + 1))]}"
    # check isatty in bash https://stackoverflow.com/questions/10022323
    # if stdout is console, turn on color output.
    [ -t 1 ] && echo "$ec[1;${color}m$@$eend" || echo "$@"
}

readonly seperator="================================================================================"

if [ $# -eq 0 ]; then
    # Bash read line does not read leading spaces https://stackoverflow.com/questions/29689172
    while IFS= read -r line; do
        colorEcho "$line"
    done
else
    for a; do
        [ $# -gt 1 ] && {
            echo "$seperator"
            echo "$a"
            echo "$seperator"
        }
        while IFS= read -r line; do
            colorEcho "$line"
        done < "$a"
    done
fi
