#!/bin/bash
# @Function
# cat lines colorfully.
#
# @Usage
#   $ ./colorful-lines
#   $ ./colorful-lines /path/to/file1
#   $ ./colorful-lines /path/to/file1 /path/to/file2
#
# @author Jerry Lee

colorEcho() {
    local color="$1"
    shift
    if [ -c /dev/stdout ] ; then
        # if stdout is console, turn on color output.
        echo -ne "\033[1;${color}m"
        echo -n "$@"
        echo -e "\033[0m"
    else
        echo "$@"
    fi
}

[ $# -eq 0 ] && files=(/dev/stdin) || files=("$@")

readonly ECHO_COLORS=(37 31 32 34 33 35 56)
COUNT=0

for file in "${files[@]}"; do
    [ ${#files[@]} -gt 1 ] && {
        echo "==== $file ===="
    }
    while read line; do
        colorEcho "${ECHO_COLORS[$((COUNT++ % ${#ECHO_COLORS[@]}))]}" "$line"
    done < "$file"
done