#!/bin/bash
# @Function
# convert to Relative Path.
#
# @Usage
#   # if 1 argument, print relative path to current dir.
#   $ ./rp /etc/apache2/httpd.conf
#   # if more than 1 argument, print relative path to last argument.
#   $ ./rp a.txt ../b.txt /etc/passwd /etc/apache2
#
# @author Jerry Lee

[ $# -eq 0 ] && {
    echo "ERROR: NO argument!"
    exit 1
}

[ $# -eq 1 ] && {
    relativeTo=.
    files=("$@")
} || {
    argv=("$@")
    argc=$#

    # Get last argument
    relativeTo="${argv[$((argc - 1))]}"
    files=( "${argv[@]:0:$((argc - 1))}" )
}

[ -f "$relativeTo" ] && relativeTo="$(dirname "$relativeTo")"

for f in "${files[@]}" ; do
    ! [ -e $f ] && {
        echo "$f does not exists!"
        continue
    }
    realpath "$f"  --relative-to="$relativeTo"
done
