#!/bin/bash
# @Function
# Open file in file explorer.
# same as xpl --selected [FILE]
#
# @Usage
#   $ ./xpf file
#
# @online-doc https://github.com/oldratlee/useful-scripts/blob/master/docs/shell.md#beer-xpl-and-xpf
# @author Jerry Lee (oldratlee at gmail dot com)

BASE=`dirname $0`
. $BASE/xpl "$@"
