#!/usr/bin/env bash
# @Function
# copy the svn remote url of current svn directory.
#
# @Usage
#   $ ./cp-svn-url
#   $ ./cp-svn-url /path/to/svn/work/dir
#
# @online-doc https://github.com/oldratlee/useful-scripts/blob/dev-2.x/docs/vcs.md#-cp-svn-url
# @author ivanzhangwb (ivanzhangwb at gmail dot com)

readonly PROG=${0##*/}
readonly PROG_VERSION='2.x-dev'

usage() {
  cat <<EOF
Usage: ${PROG} [DIR]
Copy the svn remote url of local svn directory
DIR is local svn directory, default is current directory.

Example:
    ${PROG}
    ${PROG} /path/to/svn/work/dir

Options:
    -h, --help      display this help and exit
    -V, --version   display version information and exit
EOF
  # shellcheck disable=SC2086
  exit $1
}

progVersion() {
  echo "$PROG $PROG_VERSION"
  exit
}

################################################################################
# parse options
################################################################################

for a; do
  [[ "-h" == "$a" || "--help" == "$a" ]] && usage
done

for a; do
  [[ "-V" == "$a" || "--version" == "$a" ]] && progVersion
done

################################################################################
# biz logic
################################################################################

(($# > 1)) && {
  echo At most 1 local directory is need!
  usage 1
}

readonly dir="${1:-.}"

# DO NOT declare and assign var url(as readonly) in ONE line!
#   more info see https://github.com/koalaman/shellcheck/wiki/SC2155
url="$(svn info "${dir}" | awk '/^URL: /{print $2}')"
if [ -z "${url}" ]; then
  echo "Fail to get svn url!" >&2
  exit 1
fi

copy() {
  case "$(uname)" in
  Darwin*)
    pbcopy
    ;;
  CYGWIN* | MINGW*)
    clip
    ;;
  *)
    xsel -b
    ;;
  esac
}

echo -n "${url}" | copy && echo "${url} copied!"
