#!/usr/bin/env bash
# @Function
# switch svn work directory to trunk.
#
# @Usage
#   $ ./swtrunk [<svn work dir>...]
#
# @online-doc https://github.com/oldratlee/useful-scripts/blob/dev-2.x/docs/vcs.md#-swtrunk
# @author Jerry Lee (oldratlee at gmail dot com)

colorEcho() {
  local color=$1
  shift
  # if stdout is a terminal, turn on color output.
  #   '-t' check: is a terminal?
  #   check isatty in bash https://stackoverflow.com/questions/10022323
  if [ -t 1 ]; then
    printf '\e[1;%sm%s\e[0m\n' "$color" "$*"
  else
    printf '%s\n' "$*"
  fi
}

redEcho() {
  colorEcho 31 "$@"
}

greenEcho() {
  colorEcho 32 "$@"
}

# if dirs is empty, use "."
dirs=("${dirs[@]:-.}")

for d in "${dirs[@]}"; do
  [ ! -d "${d}/.svn" ] && {
    redEcho "directory $d is not a svn work directory, ignore directory $d !"
    continue
  }
  (
    cd "$d" &&
      branches=$(svn info | grep '^URL' | awk '{print $2}') &&
      trunk=$(echo "$branches" | awk -F'/branches/' '{print $1}')/trunk &&
      if svn sw "$trunk"; then
        greenEcho "svn work directory $d switch from ${branches} to ${trunk} ."
      else
        redEcho "fail to switch $d to trunk!"
      fi
  )
done
